# fly.toml app configuration file generated for fsocicd on 2023-07-22T13:13:10+03:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "fsocicd"
primary_region = "arn"

[deploy]
  release_command = "npm run build"

[processes]
  app = "node app.js"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]

[[services.http_checks]]
    interval = 10000
    grace_period = "5s"
    method = "get"
    path = "/health"
    protocol = "http"
    restart_limit = 0
    timeout = 2000
    tls_skip_verify = false
    [services.http_checks.headers]